FROM maven:3-jdk-11

RUN mkdir /Work
COPY docker/rosetta_id /Work
ADD docker/rosetta-reqs-m2.tar.gz /root
WORKDIR /Work

RUN git clone https://github.com/REGnosys/rosetta-code-generators.git 
#&& \
#    GIT_SSH_COMMAND='ssh -i rosetta_id -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' git clone git@github.com:Cloudrisk/isda-cdm-python.git && \
WORKDIR /Work/rosetta-code-generators

RUN sed -i '/<\/project>/ i <repositories><repository><id>regnosys-snapshots<\/id><name>libs-snapshot<\/name><url>https:\/\/regnosys.jfrog.io\/regnosys\/libs-snapshot<\/url><\/repository><\/repositories>' pom.xml && \
    mvn -B archetype:generate -DgroupId=com.regnosys.rosetta.code-generators -DartifactId=python && \
    rm -rf python

COPY . ./python
RUN mvn clean install
