FROM alpine
RUN apk add --no-cache bash

# Install ssh client and git
RUN apk update && apk add --no-cache python3 py3-pip

RUN mkdir /opt/isda-cdm-code-gen 
WORKDIR /opt/isda-cdm-code-gen 
COPY build/runtime/rosetta_runtime-1.0.0-py3-none-any.whl ./runtime/rosetta_runtime-1.0.0-py3-none-any.whl
COPY build/test/serialization/ /opt/isda-cdm-code-gen/test/serialization
COPY build/python/src /opt/isda-cdm-code-gen/python/src
COPY build/python/pyproject.toml /opt/isda-cdm-code-gen/python/pyproject.toml
RUN python3 -m pip install setuptools>=62.0
RUN python3 -m pip install pylint
RUN python3 -m pip install pycodestyle
RUN python3 -m pip install yapf
RUN python3 -m pip install pydantic
RUN python3 -m pip install jsonpickle
RUN python3 -m pip install ./runtime/rosetta_runtime-1.0.0-py3-none-any.whl
WORKDIR /opt/isda-cdm-code-gen/python
RUN python3 -m pip install .
RUN python3 -m pip wheel --no-deps --only-binary :all: .
# setup test environment
RUN python3 -m pip install python_cdm-3.3.2-py3-none-any.whl
RUN python3 -m pip install pytest
WORKDIR /opt/isda-cdm-code-gen/test/
CMD python3 -m pytest

# docker build -f ./Dockerfile-Python-Rosetta-Build -t python-gen .
# docker run -i -t python-gen bash              